FROM golang
WORKDIR /app
ADD . .
RUN go get github.com/go-sql-driver/mysql && go get github.com/gorilla/mux && go get github.com/golang/glog
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o main .

FROM scratch
COPY --from=0 /app/main .
CMD ["./main"]