FROM golang
WORKDIR /app
ADD . .
RUN go get github.com/gorilla/handlers && go get github.com/go-sql-driver/mysql && go get github.com/gorilla/mux && go get github.com/golang/glog
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o main .

FROM scratch
# for testing purposes; use config map from kubernetes cluster
COPY --from=0 /app/.env/foxley_mock.json /.env/foxley_mock.json
COPY --from=0 /app/main .
CMD ["./main"]