apiVersion: v1
kind: ConfigMap
metadata:
  name: foxley-mariadb
data:
  # property-like keys
  DB_HOST: tcp(foxley.co:22113) #tcp(gomicroservices-mariadb-service)
  DB_NAME: spellweaver
  DB_USER: root
  DB_PASS: kdsaf#42348*#@$(dgaXdh28D-_93